#!/usr/bin/env bash



(
  echo '-- DO NOT EDIT - AUTOGENERATED';
  echo ''
  echo 'return {';
  curl -sS 'https://data.iana.org/TLD/tlds-alpha-by-domain.txt' | grep -v '^#' | tr '[:upper:]' '[:lower:]' | sed "s#.*#  '&',#";
  echo '}';
) > lua/gx/tlds.lua

